services:
    admin.abstract_editorial:
        abstract: true
        calls:
            - [setPoolFormatter, ['@sonata.formatter.pool']]
# Event
    admin.competition:
        class: NCBundle\Admin\Event\CompetitionAdmin
        arguments: [~, NCBundle\Entity\Event\Competition, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Competitions, group: Event }
        parent: admin.abstract_editorial
    admin.trial:
        class: NCBundle\Admin\Event\TrialAdmin
        arguments: [~, NCBundle\Entity\Event\Trial, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Trials, group: Event, show_in_dashboard: false }
        calls:
            - [setPoolFormatter, ['@sonata.formatter.pool']]
    admin.trial_result:
        class: NCBundle\Admin\Event\TrialResultAdmin
        arguments: [~, NCBundle\Entity\Event\TrialResult, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Competition Results, group: Event }
    admin.training_course:
        class: NCBundle\Admin\Event\TrainingCourseAdmin
        arguments: [~, NCBundle\Entity\Event\TrainingCourse, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Training courses, group: Event }
        parent: admin.abstract_editorial
    admin.show:
        class: NCBundle\Admin\Event\ShowAdmin
        arguments: [~, NCBundle\Entity\Event\Show, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Shows, group: Event }
        parent: admin.abstract_editorial
    admin.participant:
        class: NCBundle\Admin\Event\ParticipantAdmin
        arguments: [~, NCBundle\Entity\Event\Participant, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Participants, group: Event, show_in_dashboard: false  }
# FAQ
    admin.faq:
        class: NCBundle\Admin\Information\FAQAdmin
        arguments: [~, NCBundle\Entity\Information\FAQ, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: FAQs, group: Information }
        parent: admin.abstract_editorial
    admin.question:
        class: NCBundle\Admin\Information\QuestionAdmin
        arguments: [~, NCBundle\Entity\Information\Question, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Questions, group: Information, show_in_dashboard: false }
# Technique
    admin.technique:
        class: NCBundle\Admin\Technique\TechniqueAdmin
        arguments: [~, NCBundle\Entity\Technique\Technique, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Techniques, group: Technique }
        parent: admin.abstract_editorial
    admin.technique_execution:
        class: NCBundle\Admin\Technique\TechniqueExecutionAdmin
        arguments: [~, NCBundle\Entity\Technique\TechniqueExecution, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Technique executions, group: Technique, show_in_dashboard: false }
    admin.exercise:
        class: NCBundle\Admin\Technique\ExerciseAdmin
        arguments: [~, NCBundle\Entity\Technique\Exercise, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Exercises, group: Technique }
        parent: admin.abstract_editorial
    admin.rank_requirement:
        class: NCBundle\Admin\Technique\RankRequirementAdmin
        arguments: [~, NCBundle\Entity\Technique\RankRequirement, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Rank requirements, group: Technique }
    admin.rank:
        class: NCBundle\Admin\Technique\RankAdmin
        arguments: [~, NCBundle\Entity\Technique\Rank, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Ranks, group: Technique, show_in_dashboard: false  }
        parent: admin.abstract_editorial
    admin.rank_holder:
        class: NCBundle\Admin\Technique\RankHolderAdmin
        arguments: [~, NCBundle\Entity\Technique\RankHolder, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Rank Holders, group: Technique, show_in_dashboard: false  }
    admin.style:
        class: NCBundle\Admin\Technique\StyleAdmin
        arguments: [~, NCBundle\Entity\Technique\Style, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Styles, group: Technique }
        parent: admin.abstract_editorial
    admin.supply:
        class: NCBundle\Admin\Technique\SupplyAdmin
        arguments: [~, NCBundle\Entity\Technique\Supply, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Supplies, group: Technique }
        parent: admin.abstract_editorial
