services:
    nc.competition.sign_up.form.handler:
        class: NCBundle\Form\Handler\Event\ParticipantHandler
        arguments:
            - '@request_stack'
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'
            - '@nc.mailer'
            - '@session'
