services:
    nc.form.participant.handler:
        class: NCBundle\Form\Handler\Event\ParticipantHandler
        arguments:
            - '@request_stack'
            - '@security.token_storage'
            - '@doctrine.orm.entity_manager'
            - '@nc.service.mailer'
            - '@session'
