services:
    nc.service.mailer:
        class: NCBundle\Service\Mailer
        arguments:
            - '@twig'
            - '%nc_email%'
            - '@swiftmailer.transport'
    nc.menu.breadcrumb:
        class: NCBundle\Menu\Breadcrumb
        arguments:
            - 'nc.block'
            - 'nc.breadcrumb'
            - '@templating'
            - '@knp_menu.menu_provider'
            - '@knp_menu.factory'
            - '@request_stack'
            - '@sonata.classification.manager.collection'
            - '@NCBundle\Repository\Technique\ExerciseRepository'
            - '@NCBundle\Repository\Technique\TechniqueRepository'
            - '@NCBundle\Repository\Technique\SupplyRepository'
            - '@NCBundle\Repository\Technique\StyleRepository'
        tags:
            - { name: sonata.block }
            - { name: sonata.breadcrumb }
