application_sonata_user_reset_password_request:
    path: /request
    defaults: { _controller: ApplicationSonataUserBundle:ResetPassword:request }
application_sonata_user_reset_password_check_email:
    path: /check-email
    defaults: { _controller: ApplicationSonataUserBundle:ResetPassword:checkEmail }
application_sonata_user_reset_password_reset:
    path: /reset/{token}
    defaults: { _controller: ApplicationSonataUserBundle:ResetPassword:reset }

# Required because fos mailer uses this route
fos_user_resetting_reset:
    path: /reset/{token}
    defaults: { _controller: ApplicationSonataUserBundle:ResetPassword:reset }
