# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: .*
            context: user
            form_login:
                provider: fos_userbundle
                login_path: application_sonata_user_security_login
                check_path: application_sonata_user_security_login_check
                default_target_path: homepage
                failure_path: application_sonata_user_security_login
                use_referer: true
            logout:
                path: application_sonata_user_security_logout
                target: homepage
            anonymous: true

    # WE USE [a-z]+ FOR THE LOCALE
    access_control:
        - { path: ^/[a-z]+/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    acl:
        connection: default
