imports:
    - { resource: "@ApplicationSonataUserBundle/Resources/config/services.yml" }
    - { resource: "@NCBundle/Resources/config/services.yml" }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    NCBundle\:
        resource: '../../src/NCBundle/*'
