<?php

namespace NCFrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FAQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FAQRepository extends EntityRepository
{
}
