<?php

namespace NCFrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrialResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrialResultRepository extends EntityRepository
{
}
