home:
    resource: "@NCBundle/Resources/config/routing/home.yml"

technique:
    resource: "@NCBundle/Resources/config/routing/technique.yml"
    prefix: /{_locale}/techniques
    requirements:
        _locale: '%locales%'

exercise:
    resource: "@NCBundle/Resources/config/routing/exercise.yml"
    prefix: /{_locale}/exercises
    requirements:
        _locale: '%locales%'

rank:
    resource: "@NCBundle/Resources/config/routing/rank.yml"
    prefix: /{_locale}/ranks
    requirements:
        _locale: '%locales%'

supply:
    resource: "@NCBundle/Resources/config/routing/supply.yml"
    prefix: /{_locale}/supplies
    requirements:
        _locale: '%locales%'
