homepage:
    label: homepage
    children:
        exercise_home:
            label: exercises
            children:
                exercise_collection_view:
                    label: ~
                    children:
                        exercise_view:
                            label: ~
        technique_home:
            label: techniques
            children:
                technique_collection_view:
                    label: ~
                    children:
                        technique_view:
                            label: ~
        supply_home:
            label: supplies
            children:
                supply_collection_view:
                    label: ~
                    children:
                        supply_view:
                            label: ~
        club_home:
            label: clubs
        rank_home:
            label: ranks
            children:
                rank_view_style:
                    label: ~
                    children:
                        rank_view:
                            label: ~
        competition_home:
            label: competitions
            children:
                competition_view:
                    label: ~
                    children:
                        competition_sign_up:
                            label: sign_up
        show_home:
            label: shows
            children:
                show_view:
                    label: ~
                    children:
                        show_sign_up:
                            label: sign_up
        training_course_home:
            label: training_courses
            children:
                training_course_view:
                    label: ~
                    children:
                        training_course_sign_up:
                            label: sign_up
        application_sonata_news:
            label: news
            children:
                application_sonata_news_view:
                    label: ~
                sonata_news_view:
                    label: ~
