home:
    resource: "@NCBundle/Resources/config/routing/home.yml"

technique:
    resource: "@NCBundle/Resources/config/routing/technique.yml"
    prefix: /{_locale}/techniques
    requirements:
        _locale: '%locales%'
