home:
    resource: "@NCBundle/Resources/config/routing/home.yml"

technique:
    resource: "@NCBundle/Resources/config/routing/technique.yml"
    prefix: /{_locale}/techniques
    requirements:
        _locale: '%locales%'

exercise:
    resource: "@NCBundle/Resources/config/routing/exercise.yml"
    prefix: /{_locale}/exercises
    requirements:
        _locale: '%locales%'

rank:
    resource: "@NCBundle/Resources/config/routing/rank.yml"
    prefix: /{_locale}/ranks
    requirements:
        _locale: '%locales%'

supply:
    resource: "@NCBundle/Resources/config/routing/supply.yml"
    prefix: /{_locale}/supplies
    requirements:
        _locale: '%locales%'

competition:
    resource: "@NCBundle/Resources/config/routing/competition.yml"
    prefix: /{_locale}/competitions
    requirements:
        _locale: '%locales%'

training_course:
    resource: "@NCBundle/Resources/config/routing/trainingCourse.yml"
    prefix: /{_locale}/training-courses
    requirements:
        _locale: '%locales%'

show:
    resource: "@NCBundle/Resources/config/routing/show.yml"
    prefix: /{_locale}/shows
    requirements:
        _locale: '%locales%'

club:
    resource: "@NCBundle/Resources/config/routing/club.yml"
    prefix: /{_locale}/clubs
    requirements:
        _locale: '%locales%'
