rank_home:
    path: /
    defaults: { _controller: NCBundle:Rank:index }
rank_view_style:
    path: /view/{slug}
    defaults: { _controller: NCBundle:Rank:viewStyle }
rank_view:
    path: /view/{styleSlug}/{rankSlug}
    defaults: { _controller: NCBundle:Rank:view }
