training_course_home:
    path: /
    defaults: { _controller: NCBundle:TrainingCourse:index }
training_course_view:
    path: /view/{slug}
    defaults: { _controller: NCBundle:TrainingCourse:view }
training_course_sign_up:
    path: /sign-up/{slug}
    defaults: { _controller: NCBundle:TrainingCourse:signUp }
