parameters:
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\UserAdmin

doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    ApplicationSonataNewsBundle: ~
                    SonataNewsBundle: ~
                    SonataMediaBundle: ~
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.block.service.text:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
sonata_user:
    table:
        user_group: "user_role_group"
    class:
        user:  Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    title: Nunchaku de combat
    title_logo: /images/favicon/favicon-32x32.png
    templates:
        # Override default template
        layout: ::Admin/admin_layout.html.twig
        user_block: ::Admin/user_block.html.twig
    options:
        form_type: ~
    assets:
        extra_stylesheets:
            - bundles/sonatatranslation/css/sonata-translation.css
sonata_news:
    title:        Nunchaku de Combat
    link:         https://nunchaku-de-combat.com
    description:  https://nunchaku-de-combat.com
    salt:         'XMzY5bfxm8'
    permalink_generator: sonata.news.permalink.date
    comment:
        notification:
            emails:   [nunchaku.de.combat@gmail.com]
            from:     nunchaku.de.combat@gmail.com
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'
    table:
        post_tag: "post_tag"
    class:
        post:       Application\Sonata\NewsBundle\Entity\Post
        comment:    Application\Sonata\NewsBundle\Entity\Comment
        media:      Application\Sonata\MediaBundle\Entity\Media
        user:       Application\Sonata\UserBundle\Entity\User
sonata_media:
    db_driver: doctrine_orm
    default_context: blog
    contexts:
        blog:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                small:    { width: 150 , quality: 95}
                big:      { width: 500 , quality: 90}
                carousel: { height: 150 , quality: 90}
        club:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                small:    { width: 150 , quality: 95}
                big:      { width: 500 , quality: 90}
                carousel: { height: 150 , quality: 90}
        event:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                small:    { width: 150 , quality: 95}
                big:      { width: 500 , quality: 90}
                carousel: { height: 150 , quality: 90}
        exercise:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                small:    { width: 150 , quality: 95}
                big:      { width: 500 , quality: 90}
                carousel: { height: 150 , quality: 90}
        technique:
            download:
                strategy: sonata.media.security.public_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                small:    { width: 150 , quality: 95}
                big:      { width: 500 , quality: 90}
                carousel: { height: 150 , quality: 90}
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false
sonata_formatter:
    formatters:
#        markdown:
#            service: sonata.formatter.text.markdown
#            extensions:
#                - sonata.formatter.twig.control_flow
#                - sonata.formatter.twig.gist
#                - sonata.media.formatter.twig
#        text:
#            service: sonata.formatter.text.text
#            extensions:
#                - sonata.formatter.twig.control_flow
#                - sonata.formatter.twig.gist
#                - sonata.media.formatter.twig
#        rawhtml:
#            service: sonata.formatter.text.raw
#            extensions:
#                - sonata.formatter.twig.control_flow
#                - sonata.formatter.twig.gist
#                - sonata.media.formatter.twig
        richhtml:
            service: sonata.formatter.text.raw
            extensions:
                - sonata.formatter.twig.control_flow
                - sonata.formatter.twig.gist
                - sonata.media.formatter.twig
#        twig:
#            service: sonata.formatter.text.twigengine
#            extensions: [] # Twig formatter cannot have extensions
sonata_intl:
    timezone:
        default: Europe/Paris
sonata_translation:
    locales: [en, fr]
    default_locale: fr
    # here enable the types you need
    gedmo:
        enabled: true
    knplabs:
        enabled: false
    phpcr:
        enabled: false
