application_sonata_user_security_login:
    path: /{_locale}/login
    defaults: { _controller: ApplicationSonataUserBundle:SecurityFOSUser1:login }
    requirements:
        _locale: '%locales%'
application_sonata_user_security_login_check:
    path: /login_check
    defaults: { _controller: SonataUserBundle:SecurityFOSUser1:check }
application_sonata_user_security_logout:
    path: /logout
    defaults: { _controller: SonataUserBundle:SecurityFOSUser1:logout }
