services:
    # Listeners
    application_sonata_user.locale.listener:
        class: Application\Sonata\UserBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    application_sonata_user.user_locale.listener:
        class: Application\Sonata\UserBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    # FormTypes
    application_sonata_user.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, label: Registration, alias: application_sonata_user_registration_form_type }
    # FormHandlers
    application_sonata_user.registration.form.handler:
        class: Application\Sonata\UserBundle\Form\Handler\RegistrationHandler
        parent: sonata.user.registration.form.handler.default
        scope: request
