services:
    # FormTypes
    registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, label: Registration, alias: app_user_registration }
